### PR TITLE
Imple slack post

### PR DESCRIPTION
**Pull request by nnao45**
Hi dude.
I imple Slack web hook type.
because,
- slack webhook json format is {"text":*JSON STRING*}, execDefault is unformattable
- POST row JSON,  hard to see 😑

It's PR merge,
And config, for example,
```
filters:
  - name: MatchDefaultNamespace
    type: namespace
    namespace: default
  - name: MatchPodKind
    type: jsonpath
    path: $.involvedObject.kind
    value: Pod

destinations:
  - name: prod
    type: SlackWebHook
    url: https://hooks.slack.com/services/XXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXX

integrations:
  - name: Report
    destinations:
    - prod
    filters:
    - MatchPodKind
    - MatchDefaultNamespace
```

Looks Cool! 👍
screen shot 0030-08-12 at 14 28 44

### CODE REVIEW

**Comment by olegsu** [comment]
That's cool!
I started to implement a similar thing and just pushed branch.
As of your implementation, I think a user wants to have in his Slack more human-readable message over big JSON.
I started to implement a similar thing on my [branch](https://github.com/olegsu/iris/tree/slack#slack)
This requires more work, like template rendering and so on.
What do you think ?

**Comment by nnao45** [comment]
>I started to implement a similar thing on my branch
This requires more work, like template rendering and so on.
What do you think ?

oh, YES!! I hope template rendering feature.

And,I think...

- if type `Slack` has other paramator, it"s helpful(Legacy, Incoming webhook, )
- This integrate "Push" type Information API. But, If it can do, "Pull" type Information API(throw Webhook to k8s, return Curl to Slack from k8s).

I hope you find my PR informative.

**Comment by olegsu** [comment]
I agree, better to support all slack provided options.
If you want to implement it, including template rendering I would be happy.
Otherwise, I'll start doing it and keep you update

**Comment by nnao45** [comment]
> If you want to implement it, including template rendering I would be happy.

Okay, I will do it if I have time to make it.

**Pull request closed without merging**
