### PR TITLE
readme add for example

### PR DESCRIPTION
**Pull request by nnao45**
Hi dude.
I add example simple test.
When This exmaple using, User tset quickly with only kubernetes env(Now, I use this when test).
Do you think?
(Using test pod is [this](https://github.com/nnao45/docker-lab/tree/master/webhook-pod))

### CODE REVIEW

**Comment by olegsu** [comment]
@nnao45 Thanks for that pr.
I see what you trying to introduce but I'm not sure this is the easiest way to do so.
For example, I use https://webhook.site as in my tests, which can show the request with the body and the headers. 
Also, I can run it in a docker image locally on my machine `docker run -d --init -p 80:80 dahyphenn/webhook.site`
So maybe it will be better to create another Helm chart with this image, or yours and put a reference who to spin it locally.
Just to keep the README clean.

**Comment by nnao45** [comment]
Hi @olegsu 
Thank you for review!

> I can run it in a docker image locally on my machine docker run -d --init -p 80:80 dahyphenn/webhook.site

cool. this is good idea 🙂 

> So maybe it will be better to create another Helm chart with this image, or yours and put a reference who to spin it locally.

I also thought this.  
first time, I wonder if I should hotw to make yaml & create to request site 😢

if exists like `webhook.site` helm char & reference,
Maybe that can help users.

...If you think `reference` & `helm chart` will make more help users, I will make this. 
Do you think?

**Comment by olegsu** [comment]
@nnao45 example dir with references is a good idea.
I'm not familiar with `webhook.site`.

**Comment by nnao45** [comment]
@olegsu 
I challenge using `webhook.site` with helm chart... but, no idea 😣
so,  `helm install ./iris --values ./iris.yaml` , this command put `fixed` values.

but,  `webhook.site` make url is `filexible` values....(such as `http://localhost/e75f383a-5fd0-4edc-bcac-442b960e6ba2` , it's random uuid )
change `destinations` value is difficult.

If I will get idea, reopen.

**Pull request closed without merging**
