### PR TITLE
add-destioation.go-error-handle

### PR DESCRIPTION
**Pull request by nnao45**
Hi dude.
I think need to `pkg/dal/destination.go` error handling...
Was this done on purpose?

### CODE REVIEW

**Comment by olegsu** [comment]
@nnao45 Great!
Just make sure to promote [version](https://github.com/olegsu/iris/blob/master/VERSION) to `0.0.3` before mergin into master so new image will be created with same tag and `latest` will be updated.

**Comment by nnao45** [comment]
Hi @olegsu 
> Just make sure to promote version to 0.0.3 before mergin

ok, I am looking forward.

and, I think more fix.
I think shoud fix this funtion.

```
func (d *Destination) Exec(payload interface{}) {
	fmt.Printf("Executing destination %s\n", d.Name)
	if d.Type == "" {
		execDefault(d, payload)
		err := execDefault(d, payload)
		if err != nil {
			fmt.Printf("Error: %s\n", err)
		}
	} else if d.Type == "Codefresh" {
		execCodefresh(d, payload)
		err := execCodefresh(d, payload)
		if err != nil {
			fmt.Printf("Error: %s\n", err)
		}
	}
}
```

If user typo destions value, link `type: Codefersh`, 
no match if state & no error handle.

I think better,

```
func (d *Destination) Exec(payload interface{}) {
	fmt.Printf("Executing destination %s\n", d.Name)
	if d.Type == "" {
		execDefault(d, payload)
		err := execDefault(d, payload)
		if err != nil {
			fmt.Printf("Error: %s\n", err)
		}
	} else if d.Type == "Codefresh" {
		execCodefresh(d, payload)
		err := execCodefresh(d, payload)
		if err != nil {
			fmt.Printf("Error: %s\n", err)
		}
	} else {
		fmt.Printf("Iris can't understand this destination's type, %s\n", d.Name)
	}
}
```

do you think?
If it's change is need, I commit.

**Comment by olegsu** [comment]
@nnao45 Basically I'd like to run more complex validation before the application actually starts.
Meanwhile, I tend to agree with you that its better to have it at least somewhere.

**Comment by nnao45** [comment]
@olegsu 
Okay, I wait until the next release ☺️

**Comment by nnao45** [comment]
close this PR, once :)

**Pull request closed without merging**
